### ISSUE TITLE
Make ngrok run

### ISSUE THREAD

**Issue by kevinwiller** [rafiberlin/sose21-pm-language-and-vision-g1#17]

**Comment by ancordovag** [comment]
Already done:
1. Register in ngrok with  your github account (https://ngrok.com/) 
2. Download and install. 
In the machine (clp-pmvss21-1) run: 
`wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip`
Create folder ngrok (just to keep an order): `mkdir ngrok`
unzipp the file in the folder (unzip already installed): `unzip ngrok-stable-linux-amd64.zip`
Run this code with the code given by ngrok: `./ngrok authtoken <auth-token>`

To run every time:
3. Start HTTP tunnel in the port of the project (slurk --> port 5000). Better to make this step in a screen (`screen -S ngrok`): `ngrok http 5000` (to detach a screen: `Ctrl` + `A` and then `D`). 
A screen is displayed with a website, for example `http://57714b203887.ngrok.io`
4. Insert that URL in your local browser and play!
