### ISSUE TITLE
Check for other/better metrics besides BLEU

### ISSUE THREAD

**Issue by kat-ko** [rafiberlin/sose21-pm-language-and-vision-g1#34]
- Schlangen talked about meteor and spider
- Check maybe for something that takes entities into account

**Comment by ancordovag** [comment]
I checked the scores. You can read about it in the overleaf document. SPIDEr really convinced me. Unfortunately, there is no implementation in python, that I have found. METEOR is old, and I do not think it would be better or different than BLEU-4. SPICE, on the other hand, works differently, by focusing in the semantic and not in the syntactic. I think it would be a good complement.
